### ISSUE TITLE
DevTools discovery page is deprecated 

### ISSUE THREAD

**Issue by y-yagi** [rubycdp/cuprite#161]
`debug` method access the DevTools discovery page. But the page is deprecated now. 

![Screenshot from 2021-09-03 10-24-32](https://user-images.githubusercontent.com/987638/131936521-52fd8c46-57e1-4f06-be9f-45ec0deffd7e.png)

Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1232509

They suggest to use `chrome://inspect` instead.  But, if my understanding is correct, the inspect page can't access directly.  Should we remove accessing a page and show a message only?

**Comment by borama** [comment]
The discovery page content seems to have been removed and the page is now empty (since [this commit](https://chromium.googlesource.com/chromium/src/+/2e194e180046e5583bad6a226fa942c95e5bad52), released in [Chrome 100](https://chromium.googlesource.com/chromium/src/+log/99.0.4844.84..100.0.4896.60?pretty=fuller&n=10000)).

A workaround that works for us is to load the JSON version of the page (`http://127.0.0.1:<port>/json`) and append the first `devtoolsFrontendUrl` path to the discovery page URL.

**Comment by TylerRick** [comment]
I tried `page.driver.debug(binding)` as described at https://github.com/rubycdp/cuprite#debugging
> This will launch the browser where you can inspect the content.

but, while it does open a visible browser window, the content is empty:

![image](https://user-images.githubusercontent.com/14151/198374794-fa811b23-d539-407a-9281-4f313673951c.png)

I was considering opening an issue for it, but it sounds like this #161 is already the issue for this bug, right? It's just that as a new user who is just following the Readme and is unfamiliar with terms like "discovery page", I would not have recognized this issue as being the one to look at for my problem. Should we update the title to some thing more like what users might be searching for, like "Debug open new tab but just shows a blank page"?

Anyway, thanks for the workaround! That does work for me:
- Change the address bar to `http://127.0.0.1:<port>/json`
- Take the first `devtoolsFrontendUrl` path and change the address to use it.
    - For example: http://127.0.0.1:33369/devtools/inspector.html?ws=127.0.0.1:33369/devtools/page/A5FB1C95B850A704A50543BF7E005BA4

Could those steps be automated and done for the user automatically? Or does the driver not have a way to control the visible window?

Since the instructions for this are currently incomplete, should we update the Readme in the meantime to include the full instructions (the above "workaround") for how to inspect your actual page-under-test? Unless a fix for this is forthcoming...?

**Comment by jpheos** [comment]
I have exactly the same issue as you @TylerRick .
If a add `/json` I can find the url, but maybe you find a better solution since 2022 ?

**Comment by phikes** [comment]
I fixed it for now by monkey-patching the method which generates the debug url (put this in some file which is loaded after cuprite, e.g. `spec/support/cuprite.rb` if you autoload files in that folder):

```ruby
module Capybara
  module Cuprite
    class Driver
      def debug_url
        response = JSON.parse(Net::HTTP.get(URI(build_remote_debug_url(path: "/json"))))

        devtools_frontend_path = response[0]&.[]("devtoolsFrontendUrl")

        build_remote_debug_url path: devtools_frontend_path
      end

      private

      def build_remote_debug_url(path:)
        "http://#{browser.process.host}:#{browser.process.port}#{path}"
      end
    end
  end
end
```

I'd gladly create a PR if desired.

**Comment by route** [comment]
@phikes does it open devtools session for you? I have this message on my Mac:
<img width="488" alt="Screenshot 2023-12-11 at 11 16 12" src="https://github.com/rubycdp/cuprite/assets/414803/15f846f6-3d7b-4f7d-9f0c-5b998cd00d36">
What OS, Chrome version do you have?

**Comment by phikes** [comment]
Yes, it does. I use Chrome Canary on OS X Ventura 13.0.1. Did you try the `browser_options` I posted below? Before that I always got this error.

**Comment by route** [comment]
Missed it somehow. Could you please create a PR?

**Comment by phikes** [comment]
@route done in https://github.com/rubycdp/cuprite/pull/252

**Comment by route** [comment]
Thanks!
