### ISSUE TITLE
Also found "<<ERROR>>", "<<ERROR>>", which matched the selector but not all filters. 

### ISSUE THREAD

**Issue by fa11enangel** [rubycdp/cuprite#199]
I've tried to track down the problem, but can't figure out, how to proceed. This is the error:

```ruby
Failure:
NewsSystemTest#test_should_show_news_for_a_page [/home/runner/work/project/project/test/system/news_system_test.rb:42]:
expected to find visible css "h2" with text "My first news post" but there were no matches. Also found "<<ERROR>>", "<<ERROR>>", which matched the selector but not all filters. 
```

My setup:

* ruby 3.0.4
* rails 7.0.3
* minitest
* capybara 3.37.1
* cuprite 0.13
* setup according to [eval martians](https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing)

It fails rarely on local system, but quite often on GitHub Actions. The screenshots of the failures always show a working view with the information/text capybara is looking for.

What all these tests have in common is a within block before the lookup. It looks like:

```ruby
assert_selector 'h2', text: News.model_name.human(count: 99)

within("div##{dom_id(@news)}") do
  click_on I18n.t('more')
 end
 
 assert_selector 'h2', text: @news.title
```

This error appeared as I switched from Selenium to Cuprite. How can I try to debug it. Running the test suite with `CUPRITE_DEBUG=1 bin/rails test:system` was an idea, but I couldn't mange to reproduce the error with debugging enabled. How can I trackdown this?

**Comment by route** [comment]
I think I've seen something like this in the test suite, but I don't remember now what it was. What I remember it wasn't the issue with Cuprite, it was issue with the test suite itself. Did you try to get rid of within method if you think it's a culprit?

> It fails rarely on local system, but quite often on GitHub Actions. The screenshots of the failures always show a working view with the information/text capybara is looking for.

I think the screenshot can be made a moment later, so it's not a reliable signal.

What you can do is to turn debug log on GA like it's done for cuprite https://github.com/rubycdp/cuprite/blob/master/spec/spec_helper.rb#L121 and save artifact with failing log. It's very useful and you can attach log so that I can try to investigate. Without log it's very hard as there are many reasons to fail. 

We can also ask @SeTeM if he remembers anything about <<ERROR>> because it looks very familiar

**Comment by SeTeM** [comment]
Yeah, we had similar issues after switching from poltergeist to cuprite, but they were fixed by expecting some DOM changes after clicks

**Comment by fa11enangel** [comment]
Thank you. Now I have an idea how to proceed. If I find something interesting to this problem, I'll reopne the issue.
