### ISSUE TITLE
Should we create a new browser context on reset?

### ISSUE THREAD

**Issue by palkan** [rubycdp/cuprite#203]
## Problem

Currently, when using Cuprite with a typical Capybara setup with `Capybara.reset_sessions!` after each test, a new blank context is created **after** each test.

When running tests in a heady mode, it results in stale blank pages left open at the end of the test suite run.

Also, if a test uses multiple sessions, the second one is left open (while the first one is reused).

## Solution

Looks like removing a call to `#attach_page` from here should do the trick: https://github.com/rubycdp/cuprite/blob/2bbf3634d92af4e8b8ec3026c2b66ccf1d0590ad/lib/capybara/cuprite/browser.rb#L34

The question is: what was the purpose of adding it here (and not initializing a page lazily)?

**Comment by geoffharcourt** [comment]
Not 100% sure if this is related, but we've started seeing a lot of `Ferrum::DeadBrowserError` on specs that follow a spec that opened a second tab or pop-up window. We've confirmed this isn't running out of RAM (over 5GB free when this happens), but it seems like the first visit in the next spec might be pointing at a dead window handle somehow.

**Comment by geoffharcourt** [comment]
Note from my own poking around: it looks like `Ferrum::Browser` has the same code to call `attach_page` eagerly: https://github.com/rubycdp/cuprite/blob/2bbf3634d92af4e8b8ec3026c2b66ccf1d0590ad/lib/capybara/cuprite/browser.rb#L32-L35

**Comment by route** [comment]
I originally implemented this as Capybara wanted it. I don't really like this code, but Capybara sets some requirements.
We want to run browser lazily when we run a suite (but keep it between tests, killing in the end), same applies for a page but surprisingly only a firstly created one. If the test just starts and there's no page we should create it, after the test is done we need to destroy it, but capybara wants us to create a [new one in reset](https://github.com/teamcapybara/capybara/blob/52eaecea6d154b7d664b0032cd1cbcad4788fe65/lib/capybara/spec/session/reset_session_spec.rb#L80):

```ruby
  it 'closes extra windows', requires: [:windows] do
    @session.visit('/with_html')
    @session.open_new_window
    @session.open_new_window
    expect(@session.windows.size).to eq 3
    @session.reset_session!
    expect(@session.windows.size).to eq 1
  end

  it 'closes extra windows when not on the first window', requires: [:windows] do
    @session.visit('/with_html')
    @session.switch_to_window(@session.open_new_window)
    @session.open_new_window
    expect(@session.windows.size).to eq 3
    @session.reset_session!
    expect(@session.windows.size).to eq 1
  end
```

Same thing also applies for a running test, if the page for some reason is closed during the test we cannot lazily creata new one when we call `.page` because the close might have been intentional and in this scenario `NoSuchPageError` should have been thrown.

Thus this complication in the code. I agree with you and I'd like to make it lazy like you said, I'll skip those 2 tests (ideally we'd need to fix them upstream in capybara) and do like you said because I had the same urge to implement it like this.
