### ISSUE TITLE
Requires `Capybara.save_path` to be absolute_path, unclear error message.

### ISSUE THREAD

**Issue by davidwessman** [rubycdp/cuprite#213]
Hello!

When upgrading to Cuprite 13.0 -> 14.2 I started getting errors for in CI:

```ruby
Ferrum::Error: supply absolute path for ':save_path' option
test/system/account_test.rb:8:in `block in <class:AccountsTest>'
```

which is just a `visit` in my Rails system test.

Updating my setup from:

```ruby
Capybara.save_path = ENV.fetch('CAPYBARA_ARTIFACTS', './tmp/capybara')
```

to

```ruby
Capybara.save_path = File.expand_path(ENV.fetch('CAPYBARA_ARTIFACTS', './tmp/capybara'))
```

Could we make the error message better?

**Comment by route** [comment]
I see. While it's critical for Ferrum to get absolute path for downloads because it passes it as-is to Chrome, so that local path doesn't make sense, it's fully legitimate to Capybara to use `save_path` elsewhere in calls like `save_page` and similar. So I think we can check what is being send to Ferrum and auto convert it to absolute path, so that we don't change the behavior.
