### ISSUE TITLE
Browser did not produce websocket

### ISSUE THREAD

**Issue by Hanaffi** [rubycdp/cuprite#281]
Hello,
We are getting the mentioned error on our CI when we try to adapt Cuprite.
`Ferrum::ProcessTimeoutError: Browser did not produce websocket url within 10 second`

I don't know why does it say 10 seconds even though Im passing timeout as 300 !

```rb
 Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
      app,
      js_errors: true,
      headless: %w[0 false].exclude?(ENV["HEADLESS"]),
      slowmo: ENV["SLOWMO"]&.to_f,
      process_timeout: 300,
      timeout: 300,
      browser_options: { "no-sandbox" => true } 
    )
end
```

Please help, thanks :pray:

**Comment by navidemad** [comment]
https://github.com/rubycdp/ferrum/blob/main/lib/ferrum/browser/options.rb#L11

Try to set through ENV variable in their CI they are passing those values:
```yaml
    env:
      FERRUM_PROCESS_TIMEOUT: 25
      FERRUM_DEFAULT_TIMEOUT: 15
```
https://github.com/rubycdp/ferrum/blob/main/.github/workflows/tests.yml#L17

**Comment by route** [comment]
@Hanaffi most likely you are initializing somewhere another instance of cuprite + ferrum with default settings. It's hard to figure out as it purely depends on your environment. Try also setting ENV vars @navidemad provided and check if you have enough memory on CI because this issue is also an early sign of not sufficient memory.
